-- MySQL Script generated by MySQL Workbench
-- pią, 25 lis 2016, 23:11:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema urias-blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema urias-blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urias-blog` DEFAULT CHARACTER SET utf8 ;
USE `urias-blog` ;

-- -----------------------------------------------------
-- Table `urias-blog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urias-blog`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urias-blog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urias-blog`.`post` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `tags` TEXT NULL,
  `description` TEXT NULL,
  `author_id` INT NOT NULL,
  `location` VARCHAR(255) NULL,
  `title` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `author_id`),
  INDEX `fk_post_user1_idx` (`author_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `urias-blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `urias-blog`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `urias-blog`.`media` (
  `id` INT NOT NULL,
  `filename` VARCHAR(45) NULL,
  `post_id` INT NOT NULL,
  `type` ENUM('image', 'video') NULL,
  PRIMARY KEY (`id`, `post_id`),
  INDEX `fk_media_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_media_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `urias-blog`.`post` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
