<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Martikco photo blog">
    <meta name="keywords" content="Canada, photos, rocky mountains, USA, pictures, wildlife, blog">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1" >
    <title><?=$title;?></title>
    <style rel="stylesheet" media="all"><?= $this->minifyCss("admin"); ?></style>

    <script src="/view/js/jquery-1.12.4.min.js"></script>
    <script src="/view/js/trumbowyg.min.js"></script>
</head>
    <body>
    <!--grid wrapper-->
    <div class="grid">
    <nav class="col-1-1" id="admin-menu">
        <a href="/admin">Posts</a> |
        <a href="/admin/users">Users</a> |
        <a href="/admin/post/create"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        <a href="/logout" class="right"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i></a>
    </nav>