<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Martikco photo blog">
    <meta name="keywords" content="Canada, photos, rocky mountains, USA, pictures, wildlife, blog">
    <meta name="author" content="">
    <title><?=$title;?></title>
    <style rel="stylesheet" media="all"><?= $this->minifyCss(); ?></style>

    <script src="/view/js/jquery-1.12.4.min.js"></script>
</head>
    <body>
    <nav id="admin-menu">
        <a>Posts</a> |
        <a>Users</a> |
        <a><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
        <a href="/logout" class="right"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i></a>
    </nav>