<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Martikco photo blog">
    <meta name="keywords" content="Canada, photos, rocky mountains, USA, pictures, wildlife, blog">
    <meta name="author" content="">
    <title><?=$title;?></title>
    <link rel="stylesheet" href="/view/css/normalize.css"/>
    <link rel="stylesheet" href="/view/css/all.css"/>
    <link rel="stylesheet" href="/view/css/phones.css"/>
    <link rel="stylesheet" href="/view/css/tablets.css"/>
    <link rel="stylesheet" href="/view/css/normal.css"/>
    <script src="/view/js/jquery-1.12.4.min.js"></script>
</head>
    <body>
    <nav id="admin-menu">
        <a>Posts List</a>
        <a>Users</a>
        <a>Logout</a>
    </nav>