<html>
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="Martikco photo blog">
        <meta name="keywords" content="Canada, photos, rocky mountains, USA, pictures, wildlife, blog">
        <meta name="author" content="">
        <title><?= $title; ?></title>
        <style rel="stylesheet" media="all"><?= $this->minifyCss(); ?></style>
        <script src="/view/js/jquery-1.12.4.min.js"></script>
    </head>
    <body>
        <header>
            <a href="/" class="nolink"><?= $this->config('blog.name'); ?></a>
        </header>
        <nav>
            <div class="nav-links">
                <a href="/about">About me</a>
                <a href="/contact">Contact</a>
                <a href="/legal_disclaimer">Legal Disclaimer</a>
                <a href="/tags">Tags</a>
            </div>

            <span class="clearfix"></span>

            <div id="tools">
                <div id="search">
                    <form action="" method="GET">
                        <input type="text" name="searchText" id="searchText" placeholder="Search"/>
                        <input type="button" name="searchButton" id="searchButton"></a>
                    </form>
                </div>

                <div class="changeView">
                    <?php if ($viewName == "main") : ?><a href="/action/changeView" class="<?= $layout ?> icon nohover"></a> <?php endif; ?>
                </div>
            </div>

            <span class="clearfix"></span>
        </nav>
        <div id="content">
            <nav id="timeline"></nav>