<html>
    <head>
        <meta charset="utf-8" />
        <meta name="description" content="Martikco photo blog">
        <meta name="keywords" content="Canada, photos, rocky mountains, USA, pictures, wildlife, blog">
        <meta name="author" content="">
        <title><?=$title;?></title>
        <link rel="stylesheet" href="/view/css/normalize.css"/>
        <link rel="stylesheet" href="/view/css/all.css"/>
        <link rel="stylesheet" href="/view/css/phones.css"/>
        <link rel="stylesheet" href="/view/css/tablets.css"/>
        <link rel="stylesheet" href="/view/css/normal.css"/>
        <script src="/view/js/jquery-1.12.4.min.js"></script>
    </head>
    <body>
        <header>
            Martikco Photoblog
        </header>
        <nav>
            <div class="nav-links">
                <a href="/">Main</a>
                <a href="/about">About me</a>
                <a href="/contact">Contact</a>
                <a href="/legal_disclaimer">Legal Disclaimer</a>
                <a href="/tags">Tags</a>
            </div>

            <div id="searchbar">
                <form action="">
                    <input placeholder="Search by keywords">
                </form>
            </div>

            <div class="changeView">
                <?php if($viewName == "main" ) : ?><a href="/action/changeView" class="<?=$layout?> icon nohover"></a> <?php endif; ?>
            </div>
        </nav>
        <div id="center">