<?php $shareUrl = 'http://'.$_SERVER['HTTP_HOST'].DS."post".DS.$post["date"] .DS. $post["title"]; ?>
<article>
    <!--    main image-->
    <div id="mainImage"><img class="l-post-preview" src="<?=$post["thumbnail"]?>"></div>

    <div id="gallery">
        thumbnails
    </div>

    <div id="description"><?=$post["description"]?></div>

    <!--    share button -->
    <div class="l-post-footer">
        <div class="share-buttons">
            <a class="share-twitter icon" onclick="window.open('http://twitter.com/intent/tweet?status=<?=$post["title"]?>+<?=$shareUrl?>','_blank','width=500,height=300')"></a>
            <a class="share-facebook icon" onclick="window.open('http://www.facebook.com/sharer/sharer.php?u=<?=$shareUrl?>&title=<?=$post["title"]?>','_blank','width=500,height=300')"></a>
            <a class="share-googleplus icon" onclick="window.open('https://plus.google.com/share?url=<?=$shareUrl?>','_blank','width=500,height=300')"></a>
        </div>
        <div class="l-post-tags">#nature,#alberta,#rockymountains,#wildlife,#rawsonLake</div>
        <div class="l-post-date">
            Date: <?=$post["date"]?>
        </div>
    </div>

    <!--    disqus-->
    <div id="disqus_thread"></div>
    <script>
         var disqus_config = function () {
             this.page.url = "<?=$shareUrl?>";  // Replace PAGE_URL with your page's canonical URL variable
             this.page.identifier = "<?=$post["id"]?>"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
         };
        (function() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = '//martikco-com.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</article>